# Copyright 2020 The Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |
      Deployment template for the Platform Serices
      project registry.
    iconClass: icon-node
  name: ${NAME}-web
objects:
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${NAME}-web
      name: ${NAME}-web
    spec:
      path: ""
      port:
        targetPort: 8080-tcp
      tls:
        termination: edge
      to:
        kind: Service
        name: ${NAME}-web
        weight: 100
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}-web
      name: ${NAME}-web
    spec:
      selector:
        app: ${NAME}-web
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"${NAME}-web:${SOURCE_IMAGE_TAG}","namespace":"${SOURCE_IMAGE_NAMESPACE}"},"fieldPath":"spec.template.spec.containers[?(@.name==\"${NAME}-web\")].image"}]'
      labels:
        app: ${NAME}-web
      name: ${NAME}-web
    spec:
      strategy:
        type: RollingUpdate
      replicas: 1
      revisionHistoryLimit: 3
      selector:
        matchLabels:
          app: ${NAME}-web
      template:
        metadata:
          labels:
            app: ${NAME}-web
          name: ${NAME}-web
        spec:
          containers:
            - name: ${NAME}-web
              image: "image-registry.openshift-image-registry.svc:5000/${SOURCE_IMAGE_NAMESPACE}/${NAME}-web:${SOURCE_IMAGE_TAG}"
              imagePullPolicy: Always
              livenessProbe:
                httpGet:
                  path: /
                  port: 8080
                initialDelaySeconds: 180
                timeoutSeconds: 3
              ports:
                - containerPort: 8080
              env:
                # - name: USE_SPLUNK_FORWARDER
                #   value: ${USE_SPLUNK_FORWARDER}
                # - name: SPLUNK_AUTH_TOKEN
                #   valueFrom:
                #     secretKeyRef:
                #       name: ccup-web-splunk-auth-token
                #       key: token
                # - name: SPA_ENV_AUTH_TOKEN
                #   valueFrom:
                #     secretKeyRef:
                #       name: ccup-web-spa-env-auth-token
                #       key: token
              resources:
                requests:
                  cpu: 20m
                  memory: 256Mi
              volumeMounts:
                - name: config-vol
                  mountPath: /etc/nginx/nginx.conf
                  subPath: nginx.conf
          volumes:
            - name: config-vol
              configMap:
                name: ${NAME}-web-config
parameters:
  - description: |
      The name/acronym assigned to all of the objects defined in this template. 
      Should match what's in the config.yaml and deploy.yaml.
    displayName: Name
    name: NAME
    required: true
    value: ccup
  - description: |
      The openshift project where builds and target images are stored.
    displayName: Build Project
    name: SOURCE_IMAGE_NAMESPACE
    required: true
    value: be8465-tools
  - description: The tag of the source image.
    displayName: Source Image Tag
    name: SOURCE_IMAGE_TAG
    required: true
    #value: should be either dev, test, or prod. Pass down in command line
  - description: USE_SPLUNK_FORWARDER
    name: USE_SPLUNK_FORWARDER
    value: "true"
    required: true
  # - description: SPLUNK_AUTH_TOKEN
  #   name: SPLUNK_AUTH_TOKEN
  #   required: false
  #   valueFrom:
  #     secretKeyRef:
  #       name: log-forwarder-auth-token
  #       key: token
  # - description: SPA_ENV_AUTH_TOKEN
  #   name: SPA_ENV_AUTH_TOKEN
  #   required: true
  #   valueFrom:
  #     secretKeyRef:
  #       name: spa-env-server-service-auth-token
  #       key: token
  # - description: LOG_LEVEL
  #   name: LOG_LEVEL
  #   value: "info"
  #   required: true
