name: ccup-web-to-dev
on:
  push:
    branches:
      - "*"
    # paths:
    #   - "ccup/src/**/*.html"
    #   - "ccup/src/**/*.ts"
    #   - "ccup/src/**/*.js"
    #   - "ccup/src/**/*.scss"
    #   - "ccup/src/**/*.vue"
    #   - "ccup/package*.json"
  workflow_dispatch:
    inputs:
      force-image-build:
        description: "The default behavior of this workflow is to only build a new image + deploy to DEV when a branch is pushed to main. To override this and deploy to DEV anyway, change this to true."
        required: false
        default: false
        type: boolean
env:
  NAMESPACE: be8465-tools
  ARTIFACT_BUILD_NAME: ccup-web-artifact-build
  ARTIFACT_IMAGE_NAME: ccup-web-artifacts
  BUILD_NAME: ccup-web-image-build
  IMAGE_NAME: ccup-web
  SOURCE_IMAGE_TAG: latest
  TARGET_IMAGE_TAG: dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
      - name: Unit tests
        run: npm run test:unit
      - name: E2E tests
        run: npm run test:e2e:headless
      - name: LINTing
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: [test]
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: "true"
  image-build:
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event.inputs.force-image-build == 'true'}}
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: "mirror"
          oc: "latest"
      - name: Log in to Openshift
        run: oc login --token=${{ secrets.OpenShiftToken }} --server=${{ secrets.OpenShiftServerURL}}
      - name: Generate Artifact Build
        run: oc start-build ${ARTIFACT_BUILD_NAME} -n ${NAMESPACE} --follow
      - name: Time delay
        # to give time for Openshift to process the build so it doesn't tag the wrong image
        run: sleep 20s
      - name: Tag Artifact Build
        run: oc tag -n ${NAMESPACE} ${NAMESPACE}/${ARTIFACT_IMAGE_NAME}:${SOURCE_IMAGE_TAG} ${NAMESPACE}/${ARTIFACT_IMAGE_NAME}:${TARGET_IMAGE_TAG}
      - name: Generate Image Build
        run: oc start-build ${BUILD_NAME} -n ${NAMESPACE} --follow
      - name: Time delay
        # to give time for Openshift to process the build so it doesn't tag the wrong image
        run: sleep 20s
      - name: Tag Image Build
        run: oc tag -n ${NAMESPACE} ${NAMESPACE}/${IMAGE_NAME}:${SOURCE_IMAGE_TAG} ${NAMESPACE}/${IMAGE_NAME}:${TARGET_IMAGE_TAG}
